name: release

on:
  push:
    tags: ["v*"]

jobs:
  build:
    name: "Build distribution"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build sdist and wheel
        run: |
          rm -rf .venv
          python3 -m venv .venv
          . .venv/bin/activate
          pip install build
          python3 -m build
